# Standards: 2.2.0
---

# 1.6.1.5 - Ensure the MCS Translation Service (mcstrans) is not installed
- name: 1.6.1.5 - Ensure the MCS Translation Service (mcstrans) is not installed
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-2
    - section-1
    - "1.6.1.5"
    - scored
    - todo
