# Standards: 2.2.0
---

# 1.6.1.1 - Ensure SELinux is not disabled in bootloader configuration
- name: 1.6.1.1 - Ensure SELinux is not disabled in bootloader configuration
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-2
    - section-1
    - "1.6.1.1"
    - scored
    - todo
