# Standards: 2.2.0
---

# 4.1.1.n - Ensure the auditd.conf file is configured
#           includes the following benchmark items:
#             - 4.1.1.1 Ensure audit log storage size is configured
#             - 4.1.1.2 Ensure system is disabled when audit logs are full
#             - 4.1.1.3 Ensure audit logs are not automatically deleted


- name: 4.1.1.n - Install or update auditd.conf file
  template:
    src: templates/auditd.conf.j2
    dest: /etc/audit/auditd.conf
    mode: 0640
    owner: root
    group: root
    backup: true
# We will not restart auditd as part of the compliance remedition.
# Hosts will be rebooted.
#  notify:
#    - Restart auditd
  tags:
    - level-2
    - section-4
    - "4.1.1.1"
    - "4.1.1.2"
    - "4.1.1.3"
    - scored
