# Standards: 2.2.0
---

# 1.1.12 - Ensure separate partition exists for /var/log/audit

- name: 1.1.12 - Ensure separate partition exists for /var/log/audit
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
  when: item.mount == '/var/log/audit'
  with_items: "{{ ansible_mounts }}"
  tags:
    - level-1
    - section-1
    - "1.1.12"
    - scored
