# Standards: 2.2.0
---

# 1.1.13 - Ensure separate partition exists for /home

- name: 1.1.13 - Ensure separate partition exists for /home
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nodev']) | join(',') }}"
  when: item.mount == '/home'
  with_items: "{{ ansible_mounts }}"
  tags:
    - level-1
    - section-1
    - "1.1.13"
    - scored
