# Standards: 2.2.0
---

# 1.1.6 - Ensure separate partition exists for /var

- name: 1.1.6 - Ensure separate partition exists for /var
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nodev']) | join(',') }}"
  when: item.mount == '/var'
  with_items: "{{ ansible_mounts }}"
  tags:
    - level-1
    - section-1
    - "1.1.6"
    - scored
