# Standards: 2.2.0
---

# 1.7.2 - Ensure GDM login banner is configured
- name: 1.7.2 - Ensure GDM login banner is configured
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-1
    - "1.7.2"
    - scored
    - todo
