# Standards: 2.2.0
---

# 2.2.21 Ensure rsync service is not enabled

- name: 2.2.21 - Ensure rsync server is {{ cis_rsync_install.state }}
  yum:
    name: "{{ item.package }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ cis_rsync_install }}"
  tags:
    - level-1
    - section-2
    - "2.2.21"
    - scored

- name: 2.2.21 - If rsync server is installed set appropriate service - {{ cis_rsync_install.exception }}
  service:
    name: "{{ item.service }}"
    enabled: "{{ item.enabled }}"
    state: "{{ item.rstate }}"
  when: cis_rsync_install.state == 'present'
  with_items:
    - "{{ cis_rsync_install }}"
  tags:
    - level-1
    - section-2
    - "2.2.21"
    - scored

