# Standards: 2.2.0
---

# 5.4.1.5 - Ensure all users last password change date is in the past

- name: 5.4.1.5 - Ensure all users last password change date is in the past
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-5
    - "5.4.1.5"
    - scored
    - todo
